export const translateColor = (color, t) => {
  if (!color) return ''
  const map = {
    'noir': t('color_noir'),
    'black': t('color_noir'),
    'blanc': t('color_blanc'),
    'white': t('color_blanc'),
    'argent': t('color_argent'),
    'silver': t('color_argent'),
    'or': t('color_or'),
    'gold': t('color_or'),
    'rouge': t('color_rouge'),
    'red': t('color_rouge'),
    'bleu': t('color_bleu'),
    'blue': t('color_bleu'),
    'vert': t('color_vert'),
    'green': t('color_vert'),
    'rose gold': t('color_rose_gold'),
    'rose': t('color_rose'),
    'pink': t('color_rose'),
    'violet': t('color_violet'),
    'purple': t('color_violet'),
    'gris sidéral': t('color_gris'),
    'space gray': t('color_gris'),
    'grey': t('color_gris'),
    'minuit': t('color_minuit'),
    'midnight': t('color_minuit'),
    'lumière stellaire': t('color_lumiere'),
    'starlight': t('color_lumiere'),
    'titane naturel': t('color_titane_naturel'),
    'natural titanium': t('color_titane_naturel'),
    'titane blanc': t('color_titane_blanc'),
    'white titanium': t('color_titane_blanc'),
    'titane noir': t('color_titane_noir'),
    'black titanium': t('color_titane_noir'),
    'orange cosmique': t('color_orange_cosmique'),
    'cosmic orange': t('color_orange_cosmique'),
  }
  return map[color.toLowerCase()] || color
}
